### ISSUE TITLE
Rewording and reframing of filter terms/about page

### ISSUE THREAD

**Issue by sunniraleigh** [purcell3a/Moral-Authority#1]
Hey Angela! Interesting project. Wanted to bring this article to your attention regarding the term minority which I notice you used on your filter feature and in your about page. [](https://www.forbes.com/sites/rashaadlambert/2020/10/08/there-is-nothing-minor-about-us-why-forbes-wont-use-the-term-minority-to-classify-black-and-brown-people/?sh=520b41e17e21). The term minority is offensive, vague and seems to be counter-intuitive to the purpose of your project. When you're using "minority" here are you referring to non-white people, non-male people, non-cis people, non-straight people, people with disabilities? If the term is being used to represent people who don't identify with white cis male-ness, then it seems incorrect as the summation of people who don't hold that identity actually make up the global majority. The use of this term in your app also might offend some of your intended users as it positions them in a place of inferiority from the start, at least that is how I felt as an Asian-American. It might be more helpful for both your users and you to rephrase to what you mean more specifically. Instead of "minority-owned", if you're referring to BIPOC-owned businesses, while still an umbrella term for a large group of people, label the filter as BIPOC-owned. If you're thinking LGBTQ+ owned then definitely label it as such. It's really important to be specific in your language especially when approaching topics of morality and goodness, as those two subjects are vague themselves. The changing of these terms would also acknowledge the different oppressions "minorities" face as oppression is not a monolith and it is oppression as a tool that has made certain identities "minorities." I hope this github issue is helpful and insightful as you continue to contribute to your capstone project. Really impressive work with React and god job building a full stack app.

**Comment by purcell3a** [comment]
Sunni, 

THANK YOU for pointing this out. 

I feel quite ignorant and embarrassed for this over-sight.  Immense appreciation to you for taking the time to not only point this out but also to explain and provide alternatives! 

This will be the first thing I fix!
